---
# Copyright (c) 2019-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

services:
  feg_relay:
    host: "localhost"
    port: 9103
    proxy_type: "clientcert"
    proxy_aliases:
      s6a_proxy:
        port: 9079
      session_proxy:
        port: 9079
      swx_proxy:
        port: 9079
      csfb:
        port: 9079
      feg_hello:
        port: 9079
      ocs:
        port: 9079
      pcrf:
        port: 9079

  health:
    host: "localhost"
    port: 9107
    proxy_type: "clientcert"
