---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

enodeb_interface: eth1  # NOTE: this value must be consistent with enodeb.yml
dhcp_block_size: 15
dns_iface_name: gtp_br0

# Each address name will be forced to resolve to the given ip by dnsmasq
addresses:
  # EnodeB management server URL
  - domain: baiomc.cloudapp.net
    ip: 192.88.99.142
  - domain: baicells.chinacloudapp.cn
    ip: 192.88.99.142
