---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
#
log_level: INFO

tr069:
  interface: eth1 # NOTE: this value must be consistent with dnsmasq.conf
  port: 48080
  perf_mgmt_port: 8081
  # NOTE: this is the IP which enodeb will communicate with enodebd
  #       if this is ever changed in dnsd.yml, this needs to be updated too
  public_ip: 192.88.99.142

# Reboot eNodeB if eNodeB should be connected to MME but isn't
# This is a workaround for a bug with BaiCells eNodeB where the S1 connection
# gets into a bad state
reboot_enodeb_on_mme_disconnected: True

# Network interface to terminate S1
s1_interface: eth1
