---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

reconnect_sec: 60

# Timeout for individual streams. Revisit the time value when
# implementing a push channel over streamer.
stream_timeout: 150
