{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app.kubernetes.io/component: controller
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  {{- with .Values.controller.spec.database }}
  {{ if eq .driver "postgres" }}
  {{ .driver }}.connstr: {{ printf "dbname=%s user=%s password=%s host=%s port=%d sslmode=disable" .db .user .pass .host (.port | int) | b64enc | quote }}
  {{- end }}
  {{ if eq .driver "mysql" }}
  {{ .driver }}.connstr: {{ printf "%s:%s@%s(%s:%d)/%s" .user .pass .protocol .host (.port | int) .db | b64enc | quote }}
  {{- end }}
  {{- end }}

