# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app.kubernetes.io/component: controller
{{ include "labels" . | indent 4 }}
    {{- with .Values.controller.service.labels }}
{{ toYaml . | indent 4}}
    {{- end}}
  {{- with .Values.controller.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: controller
{{ include "selector-labels" . | indent 4 }}
  type: {{ .Values.controller.service.type }}
  ports:
    {{- with .Values.controller.service }}
    - name: web
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- range $i, $port := untilStep (.portStart | int) (.portEnd | add1 | int) 1 }}
    - name: port-{{ $i }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
    {{- end }}
