---
# List of services for magmad to control
magma_services:
  - control_proxy
  - devmand
  - td-agent-bit

# List of services that don't provide service303 interface
non_service303_services:
  - control_proxy
  - td-agent-bit

# Init system to use to control services
# Supported systems include: [systemd, runit]
init_system: systemd

# bootstrap_manager config
bootstrap_config:
  # location of the challenge key
  challenge_key: /var/opt/magma/certs/gw_challenge.key

# Flags indicating the magmad features to be enabled
enable_config_streamer: True
enable_upgrade_manager: False
enable_network_monitor: False
enable_sync_rpc: False

mconfig_modules:
  - orc8r.protos.mconfig.mconfigs_pb2
  - devmand.protos.mconfig.mconfigs_pb2

metricsd:
  collect_interval: 60 # How frequently to collect metrics samples in seconds
  sync_interval: 60 # How frequently to sync to cloud in seconds
  grpc_timeout: 10 # Timeout in seconds
  queue_length: 1000 # Number of failed samples to enqueue for resend
  # List of services for metricsd to poll
  services:
    - magmad
    - devmand
