---
################################################################################
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
################################################################################

- name: Configure /etc/resolv.conf (brittle -- need to fix systemd config)
  when: override_nameserver is defined
  block:
    - name: Delete all nameserver entries
      replace:
        path: /etc/resolv.conf
        regexp: '^nameserver .*'
        replace: ''
    - name: Add new entry
      lineinfile:
        path: /etc/resolv.conf
        state: present
        line: nameserver {{ override_nameserver }}
