---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

########################################
# Install basic tools
########################################

- name: Install basic tools
  apt:
    state: present
    pkg:
      - zip
      - unzip
      - curl
      - daemontools
      - git
      - vim
  retries: 5
  when: preburn

########################################
# Install python dependencies
########################################

- name: Install python dependencies
  apt:
    state: present
    pkg:
      - python3-pip
      - pkg-config
      - libsystemd-dev
  retries: 5
  when: preburn

########################################
# Set up control proxy
########################################

- name: Install nghttpx and its deps for Ubuntu
  apt:
    state: present
    pkg:
      - gcc
      - libssl-dev
      - libev-dev
      - libevent-dev
      - libjansson-dev
      - libjemalloc-dev
      - libc-ares-dev
      - magma-nghttpx=1.31.1-1
  retries: 5
  when: preburn and ansible_distribution == 'Ubuntu'

- name: Install nghttpx for Debian
  apt: pkg=nghttp2-proxy state=present
  retries: 5
  when: preburn and ansible_distribution == 'Debian'

#################################
# Copy service files
#################################

- name: Copy main magma service unit file
  copy:
    src: "{{ item.src }}.service"
    dest: "/etc/systemd/system/{{ item.dest }}.service"
  with_items:
    - {src: 'magma', dest: 'magma@'}
    - {src: 'magma_control_proxy', dest: 'magma@control_proxy'}
  when: full_provision
