---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- name: Create GRE tunnel gre0
  become: true
  script: create_gre_tunnel.sh

- name: Add static IP to cwag_test_br0
  become: true
  copy:
    src: 99-ovscfg.yaml
    dest: /etc/netplan

- name: Apply netplan for OVS cwag_test_br0 interface
  become: true
  shell: netplan apply

- name: Install iperf3 to use for traffic tests
  apt: pkg=iperf3 state=present update_cache=yes
