{{/*
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
*/}}

{{- if .Values.manifests.configmap_env }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $envAll.Release.Name}}-env
data:
  .env: |
{{ tuple "bin/_env.tpl" . | include "template" | indent 4 }}
  control_proxy.yml: |
{{ tuple "bin/_control_proxy.yml.tpl" . | include "template" | indent 4 }}
  bootstrap.sh: |
{{ tuple "bin/_bootstrap.sh.tpl" . | include "template" | indent 4 }}
  install_gateway.sh: |
{{ tuple "bin/_install_gateway.sh.tpl" . | include "template" | indent 4 }}
{{- end }}
