# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Config secrets for CWF module
{{- if .Values.secret.configs }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $envAll.Release.Name }}-secrets-configs
  namespace: {{ $envAll.Release.Namespace }}
  labels:
{{ tuple $envAll "cwf" "gateway" | include "labels" | indent 4 }}
data:
{{- (.Files.Glob ".configs/*.yml").AsSecrets | nindent 2 }}
{{- end }}
