{{/*
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
*/}}

{{- if .Values.manifests.service }}
{{- $envAll := . }}
{{ $serviceType := .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $envAll.Release.Name}}-health
  labels:
{{ tuple $envAll "cwf" "gateway" | include "labels" | indent 4 }}
spec:
  selector:
{{ tuple $envAll "cwf" "gateway" | include "selector-labels" | indent 6 }}
  type: ClusterIP
  ports:
    {{- with .Values.service.ports.health }}
    - name: health
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if eq $serviceType "NodePort" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end -}}
      {{- end -}}
    {{- end }}
{{- end -}}
