{{/*
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
*/}}

{{- if .Values.manifests.service }}
{{- $envAll := . }}
{{ $serviceType := .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $envAll.Release.Name}}-tcp
{{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
{{- end }}
  labels:
{{ tuple $envAll "cwf" "gateway" | include "labels" | indent 4 }}
spec:
  selector:
{{ tuple $envAll "cwf" "gateway" | include "selector-labels" | indent 6 }}
  type: "{{ .Values.service.type }}"
  ports:
    {{- with .Values.service.ports.local }}
    - name: local
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if eq $serviceType "NodePort" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end -}}
      {{- end -}}
    {{- end }}
    {{- with .Values.service.ports.cloud }}
    - name: cloud
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if eq $serviceType "NodePort" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end -}}
      {{- end -}}
    {{- end }}
    {{- with .Values.service.ports.bootstrap }}
    - name: bootstrap
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if eq $serviceType "NodePort" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end -}}
      {{- end -}}
    {{- end }}
    {{- with .Values.service.ports.ssh }}
    - name: ssh
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if eq $serviceType "NodePort" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end -}}
      {{- end -}}
    {{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
{{- end -}}
