---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Copy magma service files
  copy:
    src: "systemd/magma_{{ item }}.service"
    dest: "/etc/systemd/system/magma@{{ item }}.service"
  with_items:
    # Magma Python services
    - magmad
    - mobilityd
    - dnsd
    - eventd
    # Magma OAI services
    - mme
    # Magma third-party services
    - redis
    - pipelined
    - redirectd
    # Manhattan services
    - lighttpd
    - sessiond
  when: full_provision

- name: Copy sctpd service file
  copy:
    src: systemd/sctpd.service
    dest: /etc/systemd/system/sctpd.service
  when: full_provision

- name: Copy logrotate config file
  copy:
    src: logrotate_oai.conf
    dest: /etc/logrotate.d/oai
  when: full_provision

- name: Copy preferences file for backports
  copy: src=magma-preferences dest=/etc/apt/preferences.d/magma-preferences
  when: full_provision

- name: Copy sysctl file for core dumps
  copy: src=99-magma.conf dest=/etc/sysctl.d/99-magma.conf
  when: full_provision

- name: Create the /var/core directory
  file: path=/var/core state=directory
  when: full_provision

- name: Copy lte scripts
  copy:
    src: '{{ magma_root }}/lte/gateway/python/scripts/{{ item }}'
    dest: /usr/local/bin/{{ item }}
    force: yes
    remote_src: yes
  with_items:
    - create_oai_certs.py
    - generate_oai_config.py
  when: full_provision

- name: Create symlink for sctpd binary
  file: src='{{ c_build }}/sctpd/sctpd' path=/usr/local/sbin/sctpd state=link force=yes follow=no
  when: full_provision

- name: Create symlink for OAI mme binary
  file: src='{{ oai_build }}/oai_mme/mme' path=/usr/local/bin/mme state=link force=yes follow=no
  when: full_provision

- name: Create symlink for session_manager binary
  file: src='{{ c_build }}/session_manager/sessiond' path=/usr/local/bin/sessiond state=link force=yes follow=no
  when: full_provision

- name: Create symlink for corefile collection script
  file: src='{{ magma_root }}/lte/gateway/deploy/roles/magma/files/coredump' path=/usr/local/bin/coredump state=link force=yes follow=no
  when: full_provision

- name: Create the /var/www/local-cdn directory
  file: path=/var/www/local-cdn state=directory
  when: full_provision

- name: Create the /var/www/local-cdn/store directory
  file: path=/var/www/local-cdn/store state=directory
  when: full_provision

- name: Add Magma package directory
  become: no
  file:
    path: '{{ magma_repo }}/'
    state: directory
  when: full_provision

- name: Enable IP forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
  when: full_provision

- name: Install OpenAirInterface (OAI) dependencies
  apt:
    state: present
    update_cache: yes
    pkg:
      - check
      - libconfig8-dev
      - libgtest-dev
      - liblfds710
      - google-mock
      - libssl-dev
      - libsctp-dev
      - libtspi-dev
      - oai-asn1c
      - oai-nettle
      - oai-gnutls
      - oai-freediameter
      - prometheus-cpp-dev
  retries: 5
  when: preburn

- name: Overwrite linux 4.9 GTP module with patched module
  apt: pkg=oai-gtp=4.9-5 state=present update_cache=yes dpkg_options=force-overwrite
  retries: 5
  when: preburn

- name: Install Magma dependencies
  apt:
    state: present
    update_cache: yes
    pkg:
      # install prometheus
      - prometheus-cpp-dev
      # install openvswitch
      - openvswitch-datapath-module-4.9.0-9-amd64
      - openvswitch-switch
      - openvswitch-test
      - python-openvswitch
      - magma-libfluid
      # install lxml
      - python3-lxml
      - bridge-utils
      # install yaml parser
      - libyaml-cpp-dev
      - libgoogle-glog-dev
      # folly deps
      - libfolly-dev
      - libdouble-conversion-dev
      - libboost-chrono-dev
      - nlohmann-json-dev
      - redis-server
      - python-redis
      - magma-cpp-redis
      # Time synchronization with NTP for eventd
      - ntpdate
  retries: 5
  when: preburn

- name: Copy the gtp interface initialization definition
  copy:
    src: magma_ifaces_gtp
    dest: /etc/network/interfaces.d/gtp
  when: full_provision

- name: Preload the GTP module
  modprobe:
    name: gtp
    state: present
  when: full_provision

- name: Persist preloading the GTP module on boot
  copy:
    src: magma_modules_load
    dest: /etc/modules-load.d/magma.conf
  when: full_provision

- name: Delete the OVS bridge on system initialization
  lineinfile: dest=/etc/default/openvswitch-switch regexp='.*OVS_CTL_OPTS=.*' line='OVS_CTL_OPTS=\'--delete-bridges\'' state=present
  when: full_provision

- name: Specific Magma dependencies from backports
  apt: pkg=cmake state=present update_cache=yes
  retries: 5
  when: preburn

- name: Install C code coverage analysis dependencies
  apt: pkg=lcov state=present update_cache=yes
  retries: 5
  when: preburn

- name: Install gmock and gtest for C++ testing
  become: yes
  shell: cmake CMakeLists.txt && make && cp *.a /usr/lib
  args:
    chdir: /usr/src/{{ item }}
  with_items:
    - gtest
    - gmock
  when: preburn

- name: Install dnsmasq
  apt: pkg=dnsmasq state=present update_cache=yes
  retries: 5
  when: preburn

- name: Stop dnsmasq service
  service: name=dnsmasq state=stopped enabled=no
  when: preburn

- name: Install lighttpd
  apt: pkg=lighttpd state=present update_cache=yes
  retries: 5
  when: preburn

- name: Stop lighttpd service
  service: name=lighttpd state=stopped enabled=no
  when: preburn

- name: Restart networking to bring up linux bridge
  service:
    name: networking
    state: restarted
  when: full_provision

- name: Bring up ovs bridge
  shell: ifup --allow=ovs {{ item }}
  with_items:
    - gtp_br0
  when: full_provision

- name: Bring up interfaces
  shell: ifup {{ item }}
  with_items:
    - eth0
    - mtr0
  when: full_provision
