# ovs version on github default v2.8.1
ovs_version: "v2.8.1"
# Patches you want to apply
packages:
  - "oai-gtp_4.9-5_amd64.deb"
  - "libopenvswitch_2.8.1-1_amd64.deb"
  - "openvswitch-datapath-dkms_2.8.1-1_all.deb"
  - "openvswitch-datapath-source_2.8.1-1_all.deb"
  - "openvswitch-common_2.8.1-1_amd64.deb"
  - "openvswitch-switch_2.8.1-1_amd64.deb"

private_package: "deb http://packages.magma.etagecom.io stretch-stable main"
source_name: "packages_magma_etagecom_io"
apt_key: "http://packages.magma.etagecom.io/pubkey.gpg"
