---
################################################################################
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
################################################################################

- name: Set up Magma Federated Gateway build environment on a local machine
  hosts: feg
  become: yes
  vars:
    magma_root: /home/{{ ansible_user }}/magma
    preburn: false
    full_provision: true

  roles:
    - role: distro_snapshot
      vars:
        distro: xenial
        distro_root: "{{ lookup('env', 'FEG_DISTRO_ARCHIVE') | regex_replace('(^.*/+|)([^/]+)\\.tar\\.gz$', '\\2') }}"
        distro_archive: "{{ lookup('env', 'FEG_DISTRO_ARCHIVE') }}"
        distro_sha256: "{{ lookup('env', 'FEG_DISTRO_SHA256') }}"
    - role: gateway_dev
      vars:
        distribution: "xenial"
        repo: "dev"
        config_dir: "feg/gateway/configs"
    - role: golang
      vars:
        user: "{{ ansible_user }}"
    - role: feg_dev
      vars:
        user: "{{ ansible_user }}"
        config_dir: "feg/gateway/configs"
    - role: feg_services
