version: "3.7"

services:
  client:
    image: facebookconnectivity-southpoll-dev-docker.jfrog.io/client
    build:
      dockerfile: Dockerfile
      context: .
    secrets:
      - orc8r_api_key
      - orc8r_api_cert
