---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- name: Delete ~/go/pkg/mod if it exists already
  file:
    path: '/home/{{ ansible_user }}/go/pkg/mod'
    state: absent

- name: Create a local directory for go module cache if not present
  become: yes
  become_user: '{{ ansible_user }}'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ magma_root }}/.cache/go/pkg/mod'
    - '/home/{{ ansible_user }}/go/pkg'

- name: Symlink ~/go/pkg/mod to the cache directory
  become: yes
  become_user: '{{ ansible_user }}'
  file:
    src: '{{ magma_root }}/.cache/go/pkg/mod'
    path: '/home/{{ ansible_user }}/go/pkg/mod'
    state: link
    force: yes
