---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Set up Carrier WiFi Access Gateway Traffic Server
  hosts: trfserver
  become: true

  tasks:
    - name: Install iperf3 to use for traffic tests
    apt: pkg=iperf3 state=present update_cache=yes
