# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
#
version: '3.7'
services:
  dcsg-httpd:
    image: facebookconnectivity-southpoll-dev-docker.jfrog.io/dcsg-httpd
    restart: always
    ports:
      - 80:80
    volumes:
      - http-root:/var/www/
  dcsg-dhcpd:
    image: facebookconnectivity-southpoll-dev-docker.jfrog.io/dcsg-dhcpd
    restart: always
    network_mode: "host"
    volumes:
      - dhcp-config:/etc/dhcp/:rw
  symphony-agent:
    image: facebookconnectivity-southpoll-dev-docker.jfrog.io/symphony-agent
    restart: always
    volumes:
      - dhcp-config:/etc/dhcp/:rw
      - http-root:/var/www/:rw
    ports:
      - target: 161
        published: 161
        protocol: udp
        mode: host
      - target: 162
        published: 162
        protocol: udp
        mode: host
    tmpfs:
      - /sys/fs/cgroup
    cap_add:
    - SYS_ADMIN
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - SNOWFLAKE
      - CLOUD_ADDRESS
      - BOOTSTRAP_CLOUD_ADDRESS
volumes:
    dhcp-config:
    http-root:
