# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

{{- if .Values.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-registry
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- with .Values.docker }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (print .username ":" .password | b64enc) | b64enc }}
  {{- end }}
{{- end }}

---
# Create a copy of registry secrets in kube-system namespace for fluentd DS
{{- if .Values.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-registry
  namespace: kube-system
  labels:
{{ include "labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- with .Values.docker }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (print .username ":" .password | b64enc) | b64enc }}
  {{- end }}
{{- end }}
