# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
#
version: '3.7'
services:
  symphony-agent:
    image: facebookconnectivity-southpoll-dev-docker.jfrog.io/symphony-agent
    restart: always
    ports:
      - target: 161
        published: 161
        protocol: udp
        mode: host
      - target: 162
        published: 162
        protocol: udp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    tmpfs:
      - /sys/fs/cgroup
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    sysctls:
      - net.ipv4.ping_group_range=0 0
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - $PWD/../../../fb/config/certs/rootCA.pem:/var/opt/magma/certs/rootCA.pem:ro
      - $PWD/devman:/etc/devman:ro
    environment:
      - DEVICE_CONFIG_FILE=${DEVICE_CONFIG_FILE}
      - SNOWFLAKE=${SNOWFLAKE}
      - CLOUD_ADDRESS=${CLOUD_ADDRESS}
      - BOOTSTRAP_CLOUD_ADDRESS=${BOOTSTRAP_CLOUD_ADDRESS}
      - LOGS_CLOUD_ADDRESS=${LOGS_CLOUD_ADDRESS}
      - LOGS_CLOUD_PORT=${LOGS_CLOUD_PORT}
      - HOST_PUBLIC_ADDRESS=${HOST_PUBLIC_ADDRESS}
