{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.alertmanager.create }}
{{- $serviceName := print .Release.Name "-alertmanager" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: alertmanager
{{ include "metrics.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: alertmanager
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: alertmanager
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.alertmanager.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      volumes:
        - name: "prometheus-config"
{{ toYaml .Values.metrics.volumes.prometheusConfig.volumeSpec | indent 10 }}

      containers:
        - name: "alertmanager"
          image: {{ required "alertmanager.image.repository must be provided" .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          volumeMounts:
            - name: "prometheus-config"
              mountPath: /etc/alertmanager
              readOnly: true
          ports:
            - containerPort: 9093
          livenessProbe:
            httpGet:
              path: /
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
{{ toYaml .Values.alertmanager.resources | indent 12 }}
{{- end }}
