{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.grafana.create }}
{{- $serviceName := print .Release.Name "-grafana" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: grafana
{{ include "metrics.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      volumes:
        - name: "grafana-data"
{{ toYaml .Values.grafana.volumes.grafanaData.volumeSpec | indent 10 }}

      initContainers:
        - name: volume-mount
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /grafanaData"]
          volumeMounts:
            - name: grafana-data
              mountPath: /grafanaData

      containers:
        - name: "grafana"
          image: {{ required "grafana.image.respository must be provided" .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PROMETHEUS_HOST
              value: {{ .Values.grafana.environment.prometheusHost | quote }}
            - name: PROMETHEUS_PORT
              value: {{ .Values.grafana.environment.prometheusPort | quote }}

          volumeMounts:
            - name: "grafana-data"
              mountPath: /var/lib/grafana

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
{{- end}}
