{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "metrics.fullname" . }}-storeconfig
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
{{ include "metrics.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "metrics.fullname" . }}-storeconfig
      labels:
{{ include "metrics.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: storeconfig
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk update && apk add --no-cache coreutils
              cp -n /mnt/defaults/alertmanager.yml /mnt/configs/
              mkdir -p /mnt/configs/alert_rules && chmod +x /mnt/configs/alert_rules
              cp -n /mnt/defaults/*rules.yml /mnt/configs/alert_rules/
          volumeMounts:
            - name: defaults
              mountPath: /mnt/defaults
            - name: configs
              mountPath: /mnt/configs
      volumes:
        - name: defaults
          configMap:
            name: {{ template "metrics.fullname" . }}-defaultconfig
        - name: configs
{{ toYaml .Values.metrics.volumes.prometheusConfig.volumeSpec | indent 10 }}
