# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
---
- name: Set up Express WiFi - Magma support version Access Gateway
  hosts: localhost
  become: yes
  roles:
    - role: dhcpd
    - role: ovs
