---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

#################################
# Dev env setup
#################################

- name: Install dev time dependencies
  apt:
    state: present
    pkg:
      # Required by some go libraries
      - bzr
  when: preburn

- name: Create the $GOBIN/services directory
  file:
    path: "{{ gobin }}/services"
    state: directory
    owner: "{{ user }}"
  when: full_provision

- name: Create the $GOBIN/tools directory
  file:
    path: "{{ gobin }}/tools"
    state: directory
    owner: "{{ user }}"

- name: Create bin directory in var/opt
  file:
    path: /var/opt/magma/bin
    state: directory
    owner: "{{ user }}"
  when: full_provision

- name: Create a symlink for $GOBIN
  file:
    src: "{{ gobin }}"
    path: /var/opt/magma/bin
    state: link
    force: yes
  when: full_provision

- name: Create envdir
  file:
    path: /var/opt/magma/envdir
    state: directory
    owner: "{{ user }}"
  when: full_provision

- name: Create configs dir
  file:
    path: /var/opt/magma/configs
    state: directory
    owner: "{{ user }}"
  when: full_provision

#################################
# Copy service files for mock cores
#################################

- name: Copy mock core service file templates
  copy:
    src: "magma_{{ item }}.service"
    dest: "/etc/systemd/system/magma@{{ item }}.service"
  with_items:
    - ocs
    - pcrf
    - hss

- name: Set Go environment vars in profile
  lineinfile:
    dest: "/home/{{ user }}/.profile"
    state: present
    line: "{{ item }}"
  with_items:
    - export GO111MODULE=on
    - export GOPROXY=https://proxy.golang.org

- name: Load service registry service vars
  include_vars:
    dir: ../../../../configs/
    files_matching: service_registry.yml
    name: service_registry

- name: Add the service entries into /etc/hosts from service_registry.yml
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line='127.0.0.1 {{ item }}' state=present
  with_items: "{{ service_registry.services }}"
  when: full_provision

- name: Copy magmad_legacy.yml to config override directory
  copy:
    src: "{{ magma_root }}/{{ config_dir }}/magmad_legacy.yml"
    dest: /var/opt/magma/configs/magmad.yml
    remote_src: yes
  when: full_provision
