---
#
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
network:
  version: 2
  renderer: networkd
  ethernets:
    cwag_br0:
      dhcp4: no
      addresses:
        - 192.168.128.1/16
    gw0:
      dhcp4: no
      addresses:
        - 10.100.0.1/16
