---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

log_level: INFO

# Enable streaming from the cloud for policy updates
enable_streaming: True

# Captive Portal URL to redirect the subscribers
# If the portal is running locally, use DNSd to resolve the host to
# 192.168.128.1
captive_portal_url: http://example.com

# Config to use captive portal only for selected subscribers.
# If the profile name for the subscriber contains this substring match,
# then the subscriber is directed to the captive portal
# The default value of '' directs all users to the portal
subscriber_profile_substr_match: ''

# Interface for finding the local ip (ie 192.168.128.1)
bridge_interface: gtp_br0

# Static rule name for captive_portal redirect
# To disable, leave empty
# If disabled, allows all traffic from the subscribers
redirect_rule_name:
